### ISSUE TITLE
Question: AppleEvent handler failed error with Tyme 2018.5

### ISSUE THREAD

**Issue by bfulop** [patrickkahl/tyme2#3]
Hello,

First, thank you for creating this repo, and making it easy to query Tyme from NodeJS!

I just wanted to ask, have you also run into `AppleEvent handler failed.` errors recently?

My scripts were running fine until last weekend, but this week (after updating Tyme and the latest MacOS update), all my scripts are failing and for example

```javascript
tyme.projects()
```

throw an error.

**Comment by bfulop** [comment]
I just had the confirmation from Lars that something did break with latest update and they will try to fix it asap.

**Comment by kahl-dev** [comment]
Thanks for the info. The bug fix is out and everything works well again.
